YAML_FILE = "waves.yaml"
OUTPUT_DIR = "output"
OSC_ENVELOPE_TYPE = "exponential"  # Options: "linear", "exponential"
SAMPLE_RATE = 44100
BUFFER_SIZE = 512
VISUALISATION_ROW_HEIGHT = 10
RENDERED_MASTER_GAIN = 0.2
DO_NORMALISE_EACH_SOUND = False
DEFAULT_PLAYBACK_TIME = 4  # seconds, for nodes without explicit duration

WAIT_FOR_CHANGES_IN_WAVES_YAML = False

# Playback settings
DO_PLAY_IN_REAL_TIME = False
DO_PRE_RENDER_WHOLE_SOUND = False

# DO_PLAY_IN_REAL_TIME = True
# DO_PRE_RENDER_WHOLE_SOUND = False

# Visualisation settings
DO_VISUALISE_OUTPUT = True
DO_ONLY_VISUALISE_ONE_BUFFER = False

DISABLE_GARBAGE_COLLECTION = False
