from nodes.delay import DELAY_DEFINITION
from nodes.filter import FILTER_DEFINITION
from nodes.oscillator import OSCILLATOR_DEFINITION
from nodes.sequencer import SEQUENCER_DEFINITION

NODE_REGISTRY = [
    OSCILLATOR_DEFINITION,
    SEQUENCER_DEFINITION,
    DELAY_DEFINITION,
    FILTER_DEFINITION,
]
